/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../common";

export interface IDelegateInvestorManagementInternalInterface
  extends Interface {
  getEvent(
    nameOrSignatureOrTopic: "CustodianDelegateSet" | "CustodianDelegateUnset"
  ): EventFragment;
}

export namespace CustodianDelegateSetEvent {
  export type InputTuple = [custodian: AddressLike, delegate: AddressLike];
  export type OutputTuple = [custodian: string, delegate: string];
  export interface OutputObject {
    custodian: string;
    delegate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CustodianDelegateUnsetEvent {
  export type InputTuple = [custodian: AddressLike, delegate: AddressLike];
  export type OutputTuple = [custodian: string, delegate: string];
  export interface OutputObject {
    custodian: string;
    delegate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDelegateInvestorManagementInternal extends BaseContract {
  connect(runner?: ContractRunner | null): IDelegateInvestorManagementInternal;
  waitForDeployment(): Promise<this>;

  interface: IDelegateInvestorManagementInternalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "CustodianDelegateSet"
  ): TypedContractEvent<
    CustodianDelegateSetEvent.InputTuple,
    CustodianDelegateSetEvent.OutputTuple,
    CustodianDelegateSetEvent.OutputObject
  >;
  getEvent(
    key: "CustodianDelegateUnset"
  ): TypedContractEvent<
    CustodianDelegateUnsetEvent.InputTuple,
    CustodianDelegateUnsetEvent.OutputTuple,
    CustodianDelegateUnsetEvent.OutputObject
  >;

  filters: {
    "CustodianDelegateSet(address,address)": TypedContractEvent<
      CustodianDelegateSetEvent.InputTuple,
      CustodianDelegateSetEvent.OutputTuple,
      CustodianDelegateSetEvent.OutputObject
    >;
    CustodianDelegateSet: TypedContractEvent<
      CustodianDelegateSetEvent.InputTuple,
      CustodianDelegateSetEvent.OutputTuple,
      CustodianDelegateSetEvent.OutputObject
    >;

    "CustodianDelegateUnset(address,address)": TypedContractEvent<
      CustodianDelegateUnsetEvent.InputTuple,
      CustodianDelegateUnsetEvent.OutputTuple,
      CustodianDelegateUnsetEvent.OutputObject
    >;
    CustodianDelegateUnset: TypedContractEvent<
      CustodianDelegateUnsetEvent.InputTuple,
      CustodianDelegateUnsetEvent.OutputTuple,
      CustodianDelegateUnsetEvent.OutputObject
    >;
  };
}
