/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DelegateInvestorManagement } from "./DelegateInvestorManagement";
export type { DelegateInvestorManagementInternal } from "./DelegateInvestorManagementInternal";
export type { IDelegateInvestorManagement } from "./IDelegateInvestorManagement";
export type { IDelegateInvestorManagementInternal } from "./IDelegateInvestorManagementInternal";
