/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  UintUtils,
  UintUtilsInterface,
} from "../../../src/utils/UintUtils";

const _abi = [
  {
    inputs: [],
    name: "UintUtils__InsufficientHexLength",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220f15366eee0c3981613fc9f4c9011c3490e2b638993200d85732541888720b8be64736f6c63430008140033";

type UintUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UintUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UintUtils__factory extends ContractFactory {
  constructor(...args: UintUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      UintUtils & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): UintUtils__factory {
    return super.connect(runner) as UintUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UintUtilsInterface {
    return new Interface(_abi) as UintUtilsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): UintUtils {
    return new Contract(address, _abi, runner) as unknown as UintUtils;
  }
}
