/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as access from "./access";
export * as coupon from "./coupon";
export * as delegateInvestors from "./delegateInvestors";
export * as investors from "./investors";
export * as metadata from "./metadata";
export * as role from "./role";
export * as snapshot from "./snapshot";
export { IRegister__factory } from "./IRegister__factory";
export { IRegisterDiamond__factory } from "./IRegisterDiamond__factory";
export { RegisterDiamond__factory } from "./RegisterDiamond__factory";
export { RegisterDiamondReadable__factory } from "./RegisterDiamondReadable__factory";
export { RegisterDiamondWritable__factory } from "./RegisterDiamondWritable__factory";
