/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRegisterDiamond,
  IRegisterDiamondInterface,
} from "../../../src/register/IRegisterDiamond";

const _abi = [
  {
    inputs: [],
    name: "Proxy__ImplementationIsNotContract",
    type: "error",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class IRegisterDiamond__factory {
  static readonly abi = _abi;
  static createInterface(): IRegisterDiamondInterface {
    return new Interface(_abi) as IRegisterDiamondInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRegisterDiamond {
    return new Contract(address, _abi, runner) as unknown as IRegisterDiamond;
  }
}
