/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ERC2771Context,
  ERC2771ContextInterface,
} from "../../../src/metatx/ERC2771Context";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "trustedForwarder",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100155760c9908161001b8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c908163572b6c0514605b5750637da0a87714603457600080fd5b3460585780600319360112605857546040516001600160a01b039091168152602090f35b80fd5b905034608f576020366003190112608f576004356001600160a01b0381811691829003608b576020935416148152f35b8380fd5b5080fdfea26469706673582212200ccf5b5e5ec7de5c0d0b0d038a3772a6b43e05dcc68e0560d36c3cd0967da94b64736f6c63430008140033";

type ERC2771ContextConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC2771ContextConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC2771Context__factory extends ContractFactory {
  constructor(...args: ERC2771ContextConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ERC2771Context & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ERC2771Context__factory {
    return super.connect(runner) as ERC2771Context__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC2771ContextInterface {
    return new Interface(_abi) as ERC2771ContextInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC2771Context {
    return new Contract(address, _abi, runner) as unknown as ERC2771Context;
  }
}
