/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDelegateInvestorManagementInternal,
  IDelegateInvestorManagementInternalInterface,
} from "../../../../src/register/delegateInvestors/IDelegateInvestorManagementInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "custodian",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "delegate",
        type: "address",
      },
    ],
    name: "CustodianDelegateSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "custodian",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "delegate",
        type: "address",
      },
    ],
    name: "CustodianDelegateUnset",
    type: "event",
  },
] as const;

export class IDelegateInvestorManagementInternal__factory {
  static readonly abi = _abi;
  static createInterface(): IDelegateInvestorManagementInternalInterface {
    return new Interface(_abi) as IDelegateInvestorManagementInternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDelegateInvestorManagementInternal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDelegateInvestorManagementInternal;
  }
}
