/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DelegateInvestorManagement__factory } from "./DelegateInvestorManagement__factory";
export { DelegateInvestorManagementInternal__factory } from "./DelegateInvestorManagementInternal__factory";
export { IDelegateInvestorManagement__factory } from "./IDelegateInvestorManagement__factory";
export { IDelegateInvestorManagementInternal__factory } from "./IDelegateInvestorManagementInternal__factory";
